# Generated by Django 4.2.5 on 2023-09-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_new_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
