# Generated by Django 4.2.5 on 2023-09-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_showroom_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_image', models.ImageField(upload_to='photos')),
                ('model_range', models.CharField(max_length=100)),
                ('charging_time', models.CharField(max_length=100)),
                ('model_power', models.CharField(max_length=100)),
                ('model_torque', models.CharField(max_length=100)),
                ('model_weight', models.CharField(max_length=100)),
            ],
        ),
    ]
