# Generated by Django 4.2.5 on 2023-09-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_bike_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Award',
            new_name='Certificate',
        ),
    ]
